"""add_chunks_and_embeddings_columns

Revision ID: 07b15300d8d3
Revises: 867cd3a048a0
Create Date: 2026-01-31 17:56:43.083958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b15300d8d3'
down_revision: Union[str, Sequence[str], None] = '867cd3a048a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
