"""add_embeddings_column

Revision ID: 626907873d7c
Revises: ae30967ba204
Create Date: 2026-02-06 15:36:46.857637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '626907873d7c'
down_revision: Union[str, Sequence[str], None] = 'ae30967ba204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('session_id', sa.UUID(), nullable=False))
    op.alter_column('chat_history', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('chat_history_document_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_history', 'document_id')
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('documents', sa.Column('embeddings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('documents', sa.Column('s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 's3_url')
    op.drop_column('documents', 'embeddings')
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('chat_history', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_document_id_fkey'), 'chat_history', 'documents', ['document_id'], ['id'])
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_history', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_history', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chat_history', 'session_id')
    # ### end Alembic commands ###
