"""update_file_schema

Revision ID: e940712967ab
Revises: 4b64ce8f7252
Create Date: 2026-02-01 16:49:24.267697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e940712967ab'
down_revision: Union[str, Sequence[str], None] = '4b64ce8f7252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('file_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chat_history', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'file_id')
    # ### end Alembic commands ###
